import { Product } from "../types";
import cherryImg from "@/assets/images/catalog/cherry.png";
import condensedMilkImg from "@/assets/images/catalog/condensed_milk.png";
import peachImg from "@/assets/images/catalog/peach.png";
import plombiriniImg from "@/assets/images/catalog/plombirini.png";
import strawberryImg from "@/assets/images/catalog/strawberry.png";
import wildBerriesImg from "@/assets/images/catalog/wild_berries.png";

export const popularProducts: Product[] = [
  {
    id: "p1",
    title: "Sweet Condensed Milk",
    description:
      "Classic sweet condensed milk, perfect for desserts and coffee.",
    price: 4.99,
    weight: "100g",
    imageUrl: condensedMilkImg,
  },
  {
    id: "p2",
    title: "Plombirini Gelato",
    description: "Rich and creamy traditional plombir ice cream.",
    price: 3.49,
    weight: "100g",
    imageUrl: plombiriniImg,
  },
  {
    id: "p3",
    title: "Forest Wild Berries Mix",
    description: "A delicious blend of forest wild berries.",
    price: 6.99,
    weight: "100g",
    imageUrl: wildBerriesImg,
  },
  {
    id: "p4",
    title: "Sour Cherry Jam",
    description: "Premium sour cherries, ideal for baking or eating fresh.",
    price: 5.49,
    weight: "100g",
    imageUrl: cherryImg,
  },
  {
    id: "p5",
    title: "Juicy Peach Halves",
    description: "Juicy peach slices preserved in light syrup.",
    price: 5.99,
    weight: "100g",
    imageUrl: peachImg,
  },
  {
    id: "p6",
    title: "Strawberry Nectar",
    description: "Freshly pressed strawberry juice with pulp.",
    price: 4.29,
    weight: "100g",
    imageUrl: strawberryImg,
  },
];

export const newProducts: Product[] = [
  {
    id: "n1",
    title: "Sour Cherry Jam",
    description: "Premium sour cherries, ideal for baking or eating fresh.",
    price: 5.49,
    weight: "100g",
    imageUrl: cherryImg,
  },
  {
    id: "n2",
    title: "Juicy Peach Halves",
    description: "Juicy peach slices preserved in light syrup.",
    price: 5.99,
    weight: "100g",
    imageUrl: peachImg,
  },
  {
    id: "n3",
    title: "Strawberry Nectar",
    description: "Freshly pressed strawberry juice with pulp.",
    price: 4.29,
    weight: "100g",
    imageUrl: strawberryImg,
  },
  {
    id: "n4",
    title: "Sour Cherry Jam",
    description: "Premium sour cherries, ideal for baking or eating fresh.",
    price: 5.49,
    weight: "100g",
    imageUrl: cherryImg,
  },
  {
    id: "n5",
    title: "Juicy Peach Halves",
    description: "Juicy peach slices preserved in light syrup.",
    price: 5.99,
    weight: "100g",
    imageUrl: peachImg,
  },
  {
    id: "n6",
    title: "Strawberry Nectar",
    description: "Freshly pressed strawberry juice with pulp.",
    price: 4.29,
    weight: "100g",
    imageUrl: strawberryImg,
  },
];

export const catalogProducts: Product[] = [
  {
    id: "c1",
    title: "Sweet Condensed Milk",
    description:
      "Classic sweet condensed milk, perfect for desserts and coffee.",
    price: 4.99,
    weight: "100g",
    imageUrl: condensedMilkImg,
    category: "Candies",
    brand: "Sweettale",
    manufacturer: "Sweettale",
    inStock: true,
  },
  {
    id: "c2",
    title: "Plombirini Gelato",
    description: "Rich and creamy traditional plombir ice cream.",
    price: 3.49,
    weight: "100g",
    imageUrl: plombiriniImg,
    category: "Candies",
    brand: "Veladis",
    manufacturer: "Veladis",
    inStock: true,
  },
  {
    id: "c3",
    title: "Forest Wild Berries Mix",
    description: "A delicious blend of forest wild berries.",
    price: 6.99,
    weight: "100g",
    imageUrl: wildBerriesImg,
    category: "Cereals",
    brand: "Trapezza",
    manufacturer: "Trapezza",
    inStock: false,
  },
  {
    id: "c4",
    title: "Sour Cherry Jam",
    description: "Premium sour cherries, ideal for baking or eating fresh.",
    price: 5.49,
    weight: "100g",
    imageUrl: cherryImg,
    category: "Candies",
    brand: "Veladis",
    manufacturer: "Sweettale",
    inStock: true,
  },
  {
    id: "c5",
    title: "Juicy Peach Halves",
    description: "Juicy peach slices preserved in light syrup.",
    price: 5.99,
    weight: "100g",
    imageUrl: peachImg,
    category: "Juices",
    brand: "Sweettale",
    manufacturer: "Trapezza",
    inStock: true,
  },
  {
    id: "c6",
    title: "Strawberry Nectar",
    description: "Freshly pressed strawberry juice with pulp.",
    price: 4.29,
    weight: "100g",
    imageUrl: strawberryImg,
    category: "Juices",
    brand: "Trapezza",
    manufacturer: "Veladis",
    inStock: true,
  },
  {
    id: "c7",
    title: "Premium Oatmeal Cereals",
    description: "High fiber oatmeal cereals for a healthy breakfast.",
    price: 3.99,
    weight: "200g",
    imageUrl: wildBerriesImg,
    category: "Cereals",
    brand: "Trapezza",
    manufacturer: "Trapezza",
    inStock: true,
  },
  {
    id: "c8",
    title: "Wild Strawberry Syrup",
    description: "Concentrated wild strawberry syrup for drinks.",
    price: 7.49,
    weight: "250ml",
    imageUrl: strawberryImg,
    category: "Juices",
    brand: "Sweettale",
    manufacturer: "Veladis",
    inStock: false,
  },
  {
    id: "c9",
    title: "Chocolate Praline Candies",
    description: "Dark chocolate candies filled with rich hazelnut praline.",
    price: 12.99,
    weight: "150g",
    imageUrl: plombiriniImg,
    category: "Candies",
    brand: "Veladis",
    manufacturer: "Sweettale",
    inStock: true,
  },
  {
    id: "c10",
    title: "Golden Corn Flakes",
    description: "Crispy toasted corn flakes enriched with vitamins.",
    price: 4.59,
    weight: "300g",
    imageUrl: wildBerriesImg,
    category: "Cereals",
    brand: "Trapezza",
    manufacturer: "Veladis",
    inStock: true,
  },
  {
    id: "c11",
    title: "Premium Apple Juice",
    description: "100% natural cold-pressed apple juice.",
    price: 5.19,
    weight: "1L",
    imageUrl: peachImg,
    category: "Juices",
    brand: "Sweettale",
    manufacturer: "Trapezza",
    inStock: true,
  },
  {
    id: "c12",
    title: "Caramel Toffee Sweets",
    description: "Chewy caramel candies with milk cream centers.",
    price: 6.49,
    weight: "200g",
    imageUrl: condensedMilkImg,
    category: "Candies",
    brand: "Trapezza",
    manufacturer: "Sweettale",
    inStock: true,
  },
  {
    id: "c13",
    title: "Crunchy Honey Granola",
    description:
      "Oat granola with honey, sliced almonds, and dried cranberries.",
    price: 8.99,
    weight: "400g",
    imageUrl: wildBerriesImg,
    category: "Cereals",
    brand: "Sweettale",
    manufacturer: "Trapezza",
    inStock: false,
  },
  {
    id: "c14",
    title: "Organic Orange Juice",
    description: "Freshly squeezed oranges with extra juicy pulp.",
    price: 6.79,
    weight: "1L",
    imageUrl: strawberryImg,
    category: "Juices",
    brand: "Veladis",
    manufacturer: "Veladis",
    inStock: true,
  },
  {
    id: "c15",
    title: "Gluten-Free Muesli",
    description: "Healthy gluten-free muesli mix with pumpkin seeds.",
    price: 9.49,
    weight: "350g",
    imageUrl: wildBerriesImg,
    category: "Cereals",
    brand: "Veladis",
    manufacturer: "Sweettale",
    inStock: true,
  },
];
